steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'northamerica-northeast1-docker.pkg.dev/phx-datadissemination/django-shiny/djangoapp', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'northamerica-northeast1-docker.pkg.dev/phx-datadissemination/django-shiny/djangoapp']

  # Run Python script k8s/generate_shiny_yaml.py
  - name: 'python'
    args: ['python', './k8s/generate_shiny_yaml.py']

  # Kubectl Apply
  - name: 'gcr.io/cloud-builders/kubectl'
  # Set environment variables
    env:
    - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=django-shiny'
    args: ['apply', '-f', 'k8s']

  # Kubectl Rollout Restart
  - name: 'gcr.io/cloud-builders/kubectl'
  # Set environment variables
    env:
    - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=django-shiny'
    args: ['rollout', 'restart', 'deployment/djangoapp-deployment']
