project_name   = "pht-djangoshiny"
project_number = "130370526328"
project_id     = "pht-01hhmqtnrpf"
app_name       = "django-shiny-platform"
url            = "shiny.alpha.phac-aspc.gc.ca"
environment    = "prod"
