apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp-deployment
  labels:
    app: djangoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      volumes:
      - name: djangoapp-storage
        persistentVolumeClaim:
          claimName: djangoapp-pvc
      containers:
      - name: djangoapp
        image: northamerica-northeast1-docker.pkg.dev/phx-datadissemination/django-shiny/djangoapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: secrets
        volumeMounts:
        - mountPath: /opt/services/djangoapp/src/djangoapp/media
          name: djangoapp-storage
---
apiVersion: v1
kind: Service
metadata:
  name: djangoapp-service
spec:
  selector:
    app: djangoapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
