apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp-deployment
  labels:
    app: djangoapp
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      serviceAccountName: django-shiny-sa
      containers:
      - name: djangoapp
        image: northamerica-northeast1-docker.pkg.dev/phx-datadissemination/django-shiny/djangoapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: secrets
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: djangoapp-service
spec:
  selector:
    app: djangoapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
