# Generated by Django 4.2.6 on 2023-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shinyauth", "0002_useremailmatch_remove_shinyapp_container_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinyapp",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shinyapp",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shinyapp",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
