# Generated by Django 4.2.6 on 2023-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shinyauth", "0003_alter_shinyapp_contact_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useremailmatch",
            old_name="email_regex",
            new_name="match",
        ),
        migrations.AddField(
            model_name="useremailmatch",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("exact", "Exact (e.g. person@example.com)"),
                    ("domain", "Domain (e.g. @example.com)"),
                    ("regex", "Regular expression (e.g. .*@.*\\.gc\\.ca$)"),
                ],
                default="exact",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="useremailmatch",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
