# Generated by Django 4.2.6 on 2023-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shinyauth", "0004_rename_email_regex_useremailmatch_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyapp",
            name="mem_max",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="shinyapp",
            name="mem_min",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="shinyapp",
            name="port",
            field=models.IntegerField(default=8100),
        ),
    ]
