# Generated by Django 4.2.7 on 2024-04-03 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shinyauth", "0007_mem_gib_to_mib"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinyapp",
            name="cpu_min",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="shinyapp",
            name="mem_max",
            field=models.IntegerField(default=2048),
        ),
        migrations.AlterField(
            model_name="shinyapp",
            name="mem_min",
            field=models.IntegerField(default=1024),
        ),
        migrations.CreateModel(
            name="ShinyAppKeyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=500)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shinyauth.shinyapp",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shinyauth.usergroup",
                    ),
                ),
            ],
        ),
    ]
